Add triggering model to run a trino on query until cluster scales

diff --git a/.github/workflows/dbt_slim_ci.yml b/.github/workflows/dbt_slim_ci.yml
--- a/.github/workflows/dbt_slim_ci.yml
+++ b/.github/workflows/dbt_slim_ci.yml
@@ -56,6 +56,26 @@ jobs:
 
       - name: dbt dependencies
         run: "dbt deps"
+      
+      - name: Run dbt model on Trino if dunesql engine is used, and retry until cluster is available
+        if: matrix.engine == 'dunesql'
+        run: |
+          RETRY_COUNT=0
+          MAX_RETRIES=5
+          WAIT_TIME=30
+          
+          until [ "$RETRY_COUNT" -ge "$MAX_RETRIES" ]
+          do
+            dbt run $PROFILE --models trigger_scale && break
+            RETRY_COUNT=$((RETRY_COUNT+1))
+            if [ "$RETRY_COUNT" -ge "$MAX_RETRIES" ]; then
+              echo "Max retries reached, failing..."
+              exit 1
+            fi
+            echo "Retrying in $WAIT_TIME seconds... ($RETRY_COUNT/$MAX_RETRIES)"
+            sleep $WAIT_TIME
+          done
+
 
       - name: Check no common models between DuneSQL and Spark
         if: matrix.engine == 'dunesql'
